language: elixir

elixir:
  - 1.9
  - 1.8
  - 1.7
  - 1.6

otp_release:
  - 22.0
  - 21.0
  - 20.3
  - 19.3

script:
  - mix credo -a
  - mix test

notifications:
  recipients:
    - tobsve03@gmail.com
